services:
  rise-blog:
    container_name: rise-blog
    image: rise-blog-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5030:5000
    environment:
      - DB_TYPE=postgres
      - DB_SCHEMA=public
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis-rise
    image: redis
    environment:
      - REDIS_PORT=6379
    ports:
      - 6479:6379
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - redis:/data

  postgres:
    container_name: postgres-rise
    image: postgres:12
    ports:
      - 5452:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rise_blog
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: rise-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - backend_network
    ports:
      - '5060:80'
    depends_on:
      - postgres

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
  redis:
    driver: local